server:
  port: 4040
  mode: "dev"
mysql:
  username: root
  password: root1234
  host: 127.0.0.1
  port: 3306
  dbname: todolist
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  log_level: "debug"
  file_log_name: "./storages/logs/dev.001.log"
  max_size: 500
  max_age: 28
  max_backups: 3
  localTime: false
  compress: true
redis:
  host: 127.0.0.1
  port: 6381
  password: 
  db: 0